### ISSUE TITLE
Augmentation Evokers Breaks Addon

### ISSUE THREAD

**Issue by tance77** [shanebionic/FixRaid#1]
They are a tough cookie not really sure where to put them but I guess under damage.

`  [1473] = "ranged",  --Augmentation Evoker`

Might fix it not sure if best solution

https://github.com/shanebionic/FixRaid/pull/2

**Comment by shanebionic** [comment]
Latest Release this is fixed. Next version will build module to define them as a "support" damage, then allow options for where to sort them in the raid groups.
